@startuml
entity "学期" as SemesterU {
  + 学期ID
}
entity "学生" as StudentU {
  + 学生ID
}
entity "授業科目" as SubjectU {
  + 授業科目ID
}

StudentU ||--|| SemesterU : "1対1"
SemesterU ||..o| SubjectU : "多対多"
@enduml