@startuml
entity 商品 {
  商品コード
}

entity 入庫 {
  入庫年月日
  数量
}

entity 出庫 {
  出庫年月日
  数量
}

entity 在庫商品 {
  在庫数量
}

entity 倉庫 {
  倉庫番号
  格納先
}

商品 "1" -- "1..*" 在庫商品
在庫商品 "0..*" -- "1" 倉庫
在庫商品 "1" -- "1..*" 入庫
在庫商品 "1" -- "0..*" 出庫
@enduml