@startuml
' モデルA
package "モデルA" {
    class 部 {
      部コード
    }

    class 課 {
      課コード
    }

    class 係 {
      係コード
    }

    部 "1" --* "*" 課 : 子 (親)
    課 "1" --* "*" 係 : 子 (親)
}

' モデルB
package "モデルB" {
    class 組織B {
      組織コード
      組織レベル
    }

    組織B "0..1" --* "*" 組織B : 親
}

' モデルC
package "モデルC" {
    class 組織構造 {
      親組織コード
      子組織コード
    }

    class 組織C {
      組織コード
      組織レベル
    }

    組織構造 "1" --* "*" 組織C : 親
    組織構造 "1" --* "*" 組織C : 子
}
@enduml